### PR TITLE
Fix a grammatical issue in philosophy.md

### PR DESCRIPTION
**Pull request by getsnoopy**

### CODE REVIEW

**Comment by MasterKale** [comment]
> `ArrayBuffer`'s

Hello @getsnoopy, thank you for proposing this change. This is a personal stylistic choice that I am generally consistent with, though, because I don't like how the "s" in "`ArrayBuffer`s" looks next to an inline code block. As such I won't be incorporating this into the docs 🙂

**Comment by getsnoopy** [comment]
@MasterKale It's not a stylistic choice at all. One is a possessive, while the other is a plural. You may be confusing it with an exception for acronyms/initialisms that are 3 letters or shorter (e.g., `A's`, `CD's`), which too is only allowed in some style guides that allow it for traditional purposes. Everywhere else, it's incorrect.

**Comment by MasterKale** [comment]
This is a personal docs website for a personally maintained library that I maintain as a passion project. Unless you want to pay me on a recurring basis for editorial adherence to an agreed upon list of stylistic requirements then please respect the choices I make here. Especially when there is no danger in letting in the odd apostrophe here or there 🙂

**Comment by getsnoopy** [comment]
That's understandable, but I already did the work in this case; the PR is ready to merge. And the same could be done in the future, where you don't have spend time and effort fixing editorial stuff, but others can. Why stop other people from helping improve the project?

**Comment by MasterKale** [comment]
The PR wants to make a change I disagree with - there's no "work done" here that I would have to do myself so it's not saving me any work.

I'll continue considering editorial changes to the docs, but in this case I don't agree with the change so I'm not going to merge it. It's as simple as that.

**Comment by getsnoopy** [comment]
There's nothing to agree with, as it's a matter of fact rather than opinion. So in that sense, it is work that you would have to do yourself (assuming you want an error-free project); it's just in the "unknown unknown" category where you didn't even know that that mistake existed, but my PR brought it to your attention. Only you seem to have formed an opinion about it (despite it being a factual matter) and aren't gonna let people who have done the work fix it either.

I don't know why you thought that apparently paying you would somehow suddenly make it acceptable, but not paying you but just doing the work would not. Anyway, it sounds like you're not open to the project improving; fine. Good luck.

**Pull request closed without merging**
